### ISSUE TITLE
Keys and Certificates

### ISSUE THREAD

**Issue by rock1103** [vrk-kpa/xroad-public#16]
Hi:
In the keys and certificates,I create sign and auth key and then generate csr,but I don't know how to create sign certificate and auth certificate with csr. Can you help me to know how to get it?
thank you.

**Comment by iluwatar** [comment]
The procedure is very much specific to the CA being used. If you are using the OpenSSL based CA for testing purposes described here https://github.com/vrk-kpa/xroad-public/tree/master/utils/testca you would need to do the following:
- upload the certificate request to the CA server
- use the sign script to create the certificate e.g. `/usr/local/bin/sign request.p10 > cert.pem`

**Comment by rock1103** [comment]
Hi,
if I use security server in product environment, should I use testca or others?

**Comment by iluwatar** [comment]
The instructions are very clear about this: 

> Note that the test-CA created by the scripts is for testing purposes only and is not meant to provide a secure certification authority.

**Comment by rock1103** [comment]
Hi:
I see. but if I want to use security server in product environment, what should I do with certification, how do I create certification , such as sign and auth certifications.
thank you.

**Comment by iluwatar** [comment]
Are you trying to join some X-Road environment (e.g. Finnish or Estonian) with your security server? If yes, then you should follow environment specific instructions. For Finland the instructions are here: https://esuomi.fi/palveluntarjoajille/palveluvayla/

Or are you trying to setup your own central server with certificate authority for production use? In that case probably the wisest solution is to use some external (commercial) certificate authority.

**Comment by zjc121** [comment]
Hi:
  To configure the central server to use the test-CA   but where has the central server?

**Comment by zjc121** [comment]
•upload the certificate request to the CA server
the certificat request is generate in securate server?  use button generate CSR?

•use the sign script to create the certificate e.g.  /usr/local/bin/sign request.p10 > cert.pem  
the request.p10 is upload file?
if i want import certificat in securat server which file should i have ?   how to get the file? sign_auth? sign_sign?

**Comment by iluwatar** [comment]
The `cert.pem` file is the certificate that you should upload to the security server. Note that you need both authentication certificate and signing certificate.

**Comment by zjc121** [comment]
thank you  for your answer   
i setup central Server but get an error  
"Global configuration generation failing since '2016-11-18 20:14:01'"
i donot kown how to operate next

**Comment by iluwatar** [comment]
Probably something is missing from the central server configuration. Please see the checklist I provided in https://github.com/vrk-kpa/xroad-public/issues/14 and make sure you have done the configuration accordingly.

**Comment by zjc121** [comment]
i see the #14  and then i have another question 
Certificate Profile Info
(fully qualified class name that implements the 
 ee.ria.xroad.common.certificateprofile.
CertificateProfileInfoProvider interface)

what is this ?

thank you for help

**Comment by zjc121** [comment]
members -> member that owns the central server needs to be defined

what is owns the central server

**Comment by zjc121** [comment]
http://ip/internalconf  is 404 
#14 i can not finish the step
members and Management Services

**Comment by zjc121** [comment]
now  Management Requests has a Certificate registration Request, but it is status always waiting  how to next

**Comment by zjc121** [comment]
how to finish the step members -> member that owns the central server needs to be defined

**Comment by iluwatar** [comment]
Please study the documents in https://github.com/vrk-kpa/xroad-public/tree/master/src/doc especially the installation and user guides. With test CA you can use certificate profile info `ee.ria.xroad.common.certificateprofile.impl.FiVRKCertificateProfileInfoProvider` (this is the class that reads data from certificates).

**Comment by zjc121** [comment]
i am sorry  but i study the installation and user guides . but i do not kown how to 
⦁	An authentication certificate registration request must be **_sent from the security server to the central server**_ by the security server administrator;

because my central server cannot generate the Global configuration anchor file . it need to add a member as Management Services and the central server user guide tell me add the member need to generate a authentication certificate registration request  from securat server ,  i really read the doc ,but i do not kown , help me thank you

**Comment by zjc121** [comment]
@iluwatar  i am sorry but i study the installation and user guides . but i do not kown how to
⦁ An authentication certificate registration request must be _sent from the security server to the central server_ by the security server administrator;
because my central server cannot generate the Global configuration anchor file . it need to add a member as Management Services and the central server user guide tell me add the member need to generate a authentication certificate registration request from securat server , i really read the doc ,but i do not kown , help me thank you

**Comment by zjc121** [comment]
@iluwatar  hello   i  get a error log      xroad_distributed_files-distributed_files-globalconf

EXCEPTION MESSAGE:
Failed to generate valid global configuration: MalformedGlobalConf: An invalid XML character (Unicode: 0x8) was found in the element content of the document.


EXCEPTION BACKTRACE:
/var/tmp/xroad/jetty-center-service-temp/webapp/WEB-INF/app/controllers/conf_generator_controller.rb:117:in `create_distributable_configuration'
        /var/tmp/xroad/jetty-center-service-temp/webapp/WEB-INF/app/controllers/conf_generator_controller.rb:41:in `index'
        /var/tmp/xroad/jetty-center-service-temp/webapp/WEB-INF/gems/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
        /var/tmp/xroad/jetty-center-service-temp/webapp/WEB-INF/gems/gems/activerecord-3.2.22.2/lib/active_record/transactions.rb:208:in `transaction'
        /var/tmp/xroad/jetty-center-service-temp/webapp/WEB-INF/app/controllers/conf_generator_controller.rb:40:in `index'
        /var/tmp/xroad/jetty-center-service-temp/webapp/WEB-INF/gems/gems/transaction_isolation-1.0.3/lib/transaction_isolation/active_record/connection_adapters/postgresql_adapter.rb:49:in `isolation_level'
        /var/tmp/xroad/jetty-center-service-temp/webapp/WEB-INF/gems/gems/transaction_isolation-1.0.3/lib/transaction_isolation/active_record/base.rb:7:in `isolation_level'
        /var/tmp/xroad/jetty-center-service-temp/webapp/WEB-INF/app/controllers/conf_generator_controller.rb:39:in `index'
        /var/tmp/xroad/jetty-center-service-temp/webapp/WEB-INF/app/models/global_conf_generation_synchronizer.rb:11:in `generate'
        /var/tmp/xroad/jetty-center-service-temp/webapp/WEB-INF/app/controllers/conf_generator_controller.rb:33:in `index'
        /var/tmp/xroad/jetty-center-service-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22.2/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
        /var/tmp/xroad/jetty-center-service-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22.2/lib/abstract_controller/base.rb:167:in `process_action'
        /var/tmp/xroad/jetty-center-service-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22.2/lib/action_controller/metal/rendering.rb:10:in `process_action'
        /var/tmp/xroad/jetty-center-service-temp/webapp/WEB-INF/gems/gems/actionpack-3.2.22.2/lib/abstract_controller/callbacks.rb:18:in `process_action'
        /var/tmp/xroad/jetty-center-service-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:417:in `_run__1932231311__process_action__145269397__callbacks'
        /var/tmp/xroad/jetty-center-service-temp/webapp/WEB-INF/gems/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:405:in `__run_callback'

**Comment by zjc121** [comment]
when import certificate service have an error
Certificate profile with name 'ee.ria.xroad.common.certificateprofile.impl.FiVRKCertificateProfileInfoProvider' does not exist.

**Comment by iluwatar** [comment]
I guess the class is not available in the version you are using. Can you check what version the server reports if you open the admin user interface and go to Version page?

**Comment by zjc121** [comment]
it is my version 
Central Server version 6.8.6.20161020095957

**Comment by zjc121** [comment]
the code will update when the system restart?

**Comment by zjc121** [comment]
it is ok    my wrong   because mu testCA name has a wrong chat
thank you very much

**Comment by rajotico** [comment]
Hi,
I am using the TestCA scripts to sign my certificates. I am getting this error when I try to import the certificate into the security server: "Cannot read member identifier from signing certificate: Malformed serial number: 00000003"

I noticed the serial number is the member code I assigned in the central server to this member. It first complained that it must have 8 digits and that's why I use all those zeros. I was also reading both the CS-UG and SS-UG documents but neither one explains how this member code is used as part of the certificate serial number. Any suggestions would be greatly appreciated. Thanks!

**Comment by iluwatar** [comment]
The instructions for creating the certificate requests are country (and sometimes version) specific. For Finland there are good step-by-step instructions starting from here https://confluence.csc.fi/display/Palveluvayla/Harjoitus+osa+1+-+ohjelmiston+asennus. Unfortunately the documents are in Finnish but hopefully you can use browser's translate to English functionality to understand it a bit better. Also, I recommend that you build the software packages from the source code by yourself since the ones that come from the x-road.eu repository are different and the instructions don't directly apply to them.

**Comment by kudramh** [comment]
Hi, when importing the sign.pem certificate, the service have the following error: Failed to import certificate: Could not find identifier decoder: 'ee.ria.xroad.common.certificateprofile.impl.FiVRKCertificateProfileInfoProvider'
I've compiled and installed from repo the CentralServer and SecurityServer, and also the TSACA services are running...I don't find this class also in the repo...

**Comment by iluwatar** [comment]
I think this has to do with how the certification services have been configured on the central server. For the 6.7.13 version that can be built from this repository's source code you should configure

Central server > Certification services > Select the certification service from the list and click edit > CA Settings > Member code/identifier extractor method = "ee.ria.xroad.common.util.FISubjectClientIdDecoder.getSubjectClientId"

Please notice that the configuration is different for 6.8x and newer.

**Comment by kudramh** [comment]
Hi Iluwatar, this functioned as expected with the Test-TSA/CA. 
Thanks 
Marduk

**Comment by leviduran** [comment]
Hi Iluwatar, in regards to the question asked by kudramh. If using  a production grade CA...would it be safe to assume that it's necessary to code a similar extracting method specific for the CA implementation that I'm using?. Thanks in advance!

**Comment by pkivima** [comment]
Hi,

That's correct. The extracting method must implement the certificate profile used by the certificate authority.

Thanks,
Petteri

**Comment by hanhaka** [comment]
Issue has been solved or no feedback from requester has been received.
